fix(ktlint): support ktlint_disabled_rules in 0.47+
diffplug/spotless pull request #1378
Opened 2022-10-19 15:16 UTC by bcmedeiros

A fix for the `ktlint_disabled_rules` issue reported in https://github.com/diffplug/spotless/issues/1374.

`ktlintDisabledRulesProperty` is not enumerated in `DefaultEditorConfigProperties.INSTANCE.getEditorConfigProperties()` for some reason, so in order to support it in a backwards compatible (down to 0.47) way, we have to manually add it.

2022-10-19 20:54 UTC, nedtwigg requested changes
Needs two things:

- changelog entries (all three changelogs)
- tests are failing

2022-10-21 02:19 UTC, bcmedeiros commented
@nedtwigg adjustments made, I hope I got the release notes right. Let me know if you need anything else.

2022-10-21 20:08 UTC, nedtwigg approved these changes
Perfect, thanks very much!

2022-10-21 20:09 UTC, merged

2022-11-24 22:21 UTC, nedtwigg commented
Published in `plugin-gradle 6.12.0` and `plugin-maven 2.28.0`.