Feature/gherkin
diffplug/spotless pull request #1649
Opened 2023-04-01 18:25 UTC by blacelle

This follows the work in https://github.com/diffplug/spotless/pull/928 (thanks @jamietanna).

It is reworked to:

1. be synced with main
2. Rely on gherkin-utils core module
3. Lost ability to customize the indentation through this Gherkin formatter. It should remain available through standard Spotless indentation
4. Added maven integration

2023-04-01 18:26 UTC, blacelle commented on .editorconfig
> +[/testlib/src/main/resources/**]
@nedtwigg I (again) got issues when copy-pasting from Jupiter actual results to test resoures, as IntelliJ was automatically reformatting my clipboard content.

2023-04-01 18:53 UTC, jamietanna commented
Thanks for this, but note that there are some issues upstream with how it treats certain things like whitespace and tables, which is also what blocked my original PR with my library 😅

2023-04-05 18:28 UTC, nedtwigg commented
@blacelle Would you like me to merge this now, or do you want to wait for https://github.com/cucumber/gherkin-utils/pull/20?

2023-04-05 18:32 UTC, nedtwigg requested changes
Instead of `gherkin { simple()`, I would name it `gherkin { gherkinUtils()`.

2023-04-05 18:32 UTC, nedtwigg commented on plugin-gradle/README.md
> +Uses a Gherkin pretty-printer that optionally allows configuring the number of spaces that are used to pretty print objects:
As per other formatters (e.g. [scalafmt](https://github.com/diffplug/spotless/tree/main/plugin-gradle#scalafmt)) link to

- https://github.com/cucumber/gherkin-utils
- https://github.com/cucumber/gherkin-utils/blob/main/CHANGELOG.md

2023-04-05 18:32 UTC, nedtwigg commented on plugin-maven/CHANGES.md
> +* Added support for Gherkin feature files ([1649](https://github.com/diffplug/spotless/issues/1649)).
`#1649` vs `1649`

2023-04-05 18:32 UTC, nedtwigg commented on CHANGES.md
> +* Added formatter for Gherkin feature files ([1649](https://github.com/diffplug/spotless/issues/1649)).
`#1649` vs `1649`

2023-04-05 19:00 UTC, blacelle commented
I would merge at your earlier convenience. Let me implement the requested changes.

2023-04-05 19:10 UTC, blacelle commented
This should be OK. Thanks @nedtwigg

2023-04-05 21:51 UTC, nedtwigg approved these changes

2023-04-05 22:09 UTC, merged

2023-04-06 03:50 UTC, nedtwigg commented
Published in `plugin-gradle 6.18.0` and `plugin-maven 2.36.0`.