Skip execution in incremental (m2e) builds by default
diffplug/spotless pull request #2059
Opened 2024-03-02 14:27 UTC by kwin

Clear stale messages during "check" mojo
Allow to parameterize message severity
Add Spotless prefix to messages

This closes #1814
This closes #2037

Please **DO NOT FORCE PUSH**. Don't worry about messy history, it's easier to do code review if we can tell what happened after the review, and force pushing breaks that.

Please make sure that your [PR allows edits from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/).  Sometimes its faster for us to just fix something than it is to describe how to fix it.

![Allow edits from maintainers](https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)

After creating the PR, please add a commit that adds a bullet-point under the `[Unreleased]` section of [CHANGES.md](https://github.com/diffplug/spotless/blob/main/CHANGES.md), [plugin-gradle/CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md), and [plugin-maven/CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-maven/CHANGES.md) which includes:

- [ ] a summary of the change
- either
    - [ ] a link to the issue you are resolving (for small changes)
    - [ ] a link to the PR you just created (for big changes likely to have discussion)

If your change only affects a build plugin, and not the lib, then you only need to update the `plugin-foo/CHANGES.md` for that plugin.

If your change affects lib in an end-user-visible way (fixing a bug, updating a version) then you need to update `CHANGES.md` for both the lib and all build plugins.  Users of a build plugin shouldn't have to refer to lib to see changes that affect them.

This makes it easier for the maintainers to quickly release your changes :)

2024-03-18 15:22 UTC, kwin commented
@nedtwigg Anything I can do to speed up the review process?

2024-04-03 06:17 UTC, nedtwigg requested changes
Great PR, sorry it sat for a while.

Do you think it's okay to prefix these flags with `m2e`? I want to make sure they don't add confusion for non-eclipse users.

2024-04-03 06:17 UTC, nedtwigg commented on plugin-maven/src/main/java/com/diffplug/spotless/maven/AbstractSpotlessMojo.java
> +	protected boolean enableForIncrementalBuild;
`m2eEnableForIncrementalBuild`

2024-04-03 06:17 UTC, nedtwigg commented on plugin-maven/README.md
> +    <enableForIncrementalBuild>true</enableForIncrementalBuild><!-- this is false by default -->
`m2eEnableForIncrementalBuild`

2024-04-03 06:17 UTC, nedtwigg commented on plugin-maven/README.md
> +    <incrementalBuildMessageSeverity>ERROR</incrementalBuildMessageSeverity><!-- WARNING or ERROR -->
`m2eIncrementalBuildMessageSeverity`

2024-04-03 06:17 UTC, nedtwigg commented on plugin-maven/src/main/java/com/diffplug/spotless/maven/AbstractSpotlessMojo.java
> +		if (buildContext.isIncremental() && !enableForIncrementalBuild) {
`m2eEnableForIncrementalBuild`

2024-04-03 06:17 UTC, nedtwigg commented on plugin-maven/src/main/java/com/diffplug/spotless/maven/SpotlessCheckMojo.java
> +	private MessageSeverity incrementalBuildMessageSeverity;
`m2eIncrementalBuildMessageSeverity`

2024-04-03 07:04 UTC, kwin commented
> Do you think it's okay to prefix these flags with m2e? I want to make sure they don't add confusion for non-eclipse users.

I only implement an m2e agnostic API, namely https://github.com/codehaus-plexus/plexus-build-api. However the only known user of that API is currently m2e. Still I would rather lean towards keeping the m2e agnostic names, because at least theoretically they could be used by any IDE/incremental build tool....

2024-04-03 15:30 UTC, nedtwigg commented
If another IDE comes along and implements the IDE we can add an alias for that IDE too, but in the meantime if the only users today or in the immediate future is `m2e`, I don't want to get support requests from users of other IDEs.

2024-04-03 16:29 UTC, nedtwigg commented on plugin-maven/README.md
> +    <m2eEnableForIncrementalBuild>true</m2eEnableForIncrementalBuild><!-- this is false by default -->
or maybe `m2eIncrementalBuildMessages`

2024-04-03 16:31 UTC, kwin commented on plugin-maven/README.md
> +    <m2eEnableForIncrementalBuild>true</m2eEnableForIncrementalBuild><!-- this is false by default -->
`m2eIncrementalBuild` is too fuzzy for me, `m2eIncrementalBuildMessages` sounds better.

2024-04-03 16:33 UTC, nedtwigg commented on plugin-maven/README.md
> +    <m2eEnableForIncrementalBuild>true</m2eEnableForIncrementalBuild><!-- this is false by default -->
That works for me :)

2024-04-04 08:23 UTC, kwin commented on plugin-maven/README.md
> +    <m2eEnableForIncrementalBuild>true</m2eEnableForIncrementalBuild><!-- this is false by default -->
After having a second thought, I think having only one parameter is over-simplifying things, as we talk about two different goals:
1. apply
1. check

The message severity is only ever useful for the latter, while enabling applies to both.

2024-04-04 15:25 UTC, nedtwigg commented on plugin-maven/README.md
> +    <m2eEnableForIncrementalBuild>true</m2eEnableForIncrementalBuild><!-- this is false by default -->
If `m2eEnableForIncrementalBuild` is false, then `m2eIncrementalBuildMessages` has no effect, correct? And if `m2eEnableForIncrementalBuild` is true, would it ever make sense for `m2eIncrementalBuildMessageSeverity ` to be `NONE` or `SILENT`?

I might be wrong, but this seems like having a separate switch for the fuel pump on a car.

2024-04-04 15:53 UTC, kwin commented on plugin-maven/README.md
> +    <m2eEnableForIncrementalBuild>true</m2eEnableForIncrementalBuild><!-- this is false by default -->
> If m2eEnableForIncrementalBuild is false, then m2eIncrementalBuildMessages has no effect, correct?

That is correct.

> And if m2eEnableForIncrementalBuild is true, would it ever make sense for m2eIncrementalBuildMessageSeverity  to be NONE or SILENT?

No, but the point is that noone expects that `m2eIncrementalBuildMessageSeverity` or `m2eIncrementalBuildMessages ` would toggle off the incremental build at all.

> but this seems like having a separate switch for the fuel pump on a car.

For me it feels more like adjusting your AC will implicitly also start your car ;-)

2024-04-04 15:58 UTC, nedtwigg commented on plugin-maven/README.md
> +    <m2eEnableForIncrementalBuild>true</m2eEnableForIncrementalBuild><!-- this is false by default -->
That's not such a bad idea if the car can't run without A/C. But whatever, I usually defer to the people who are gonna use the thing.

Only thing missing now is a changelog entry.

2024-04-04 16:23 UTC, kwin commented on plugin-maven/README.md
> +    <m2eEnableForIncrementalBuild>true</m2eEnableForIncrementalBuild><!-- this is false by default -->
Done

P.S. I would consider `m2eIncrementalBuildMessageSeverity` advanced setting (rarely adjusted) while `m2eEnableForIncrementalBuild` is a basic setting (easy to understand for everyone, more often adjusted). Hope this is enough justification for keep both separate, but this is definitely my last argument to this discussion :-)

2024-04-07 00:48 UTC, nedtwigg approved these changes

2024-04-07 00:48 UTC, merged