Fix spotlessFiles parameter tests
diffplug/spotless pull request #737
Opened 2020-11-15 17:51 UTC by driv

- `(`,`|` and `)` should not be escaped with `\`, otherwise they get
  interpreted as literals and no file matches
- On Windows paths use backslashes, so `\\\\` has to be used.
2 for java strings and 2 since this parameter is treated as a regex.

Few remarks:
- No issue for this, I just couldn't make it run `check` on Windows. Changes only on Tests.
- I don't have a unix machine right now to test it on.
- I'm not sure if/how it was even running for unix. `.*/src/main/java/test\\(1\\|3\\).java` should have been interpreted as literal.

2020-11-16 01:07 UTC, nedtwigg requested changes
Hmmm... the unix tests were passing, but now they are failing.  I see your point about the parens being interpreted as literal, I'm not sure why this worked before, but it did.

2020-11-16 01:08 UTC, nedtwigg commented
Also, needs a changelog entry in `plugin-maven/CHANGES.md`. Can use this PR as the link.

2020-11-16 07:12 UTC, driv commented
Any idea what's going on with the npm one? Does it use a different java version?

2020-11-16 17:33 UTC, nedtwigg commented
Spotless is JRE 8+
https://github.com/diffplug/spotless/blob/23f8d694a0c93b9d2c5a2343f34b4ffe9ccaeab5/.circleci/config.yml#L92-L107

The Path method you are using is present in [JRE 11](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Path.html#of(java.net.URI)), but not in [JRE 8](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html).

2020-11-17 21:16 UTC, merged

2020-11-17 21:16 UTC, nedtwigg commented
Thanks for the fix!

2020-11-17 21:23 UTC, driv commented on plugin-maven/src/test/java/com/diffplug/spotless/maven/SpecificFilesTest.java
> +		return System.getProperty("os.name").startsWith("Windows");
I was 2 seconds away from pushing this change. :)

2020-11-17 22:16 UTC, nedtwigg commented on plugin-maven/src/test/java/com/diffplug/spotless/maven/SpecificFilesTest.java
> +		return System.getProperty("os.name").startsWith("Windows");
Sorry, guess my review was sloppy. "Is the project better now?" If the answer is yes, then I try to get people's stuff merged-in ASAP - I try to err on the side of not blocking people once I'm confident that it's not making new bugs or vulnerabilities. It's not a big deal to have this duplicated. If you want to swap this out in some future PR then fine, if it stays duplicated that's fine too.

2020-11-18 11:10 UTC, driv commented on plugin-maven/src/test/java/com/diffplug/spotless/maven/SpecificFilesTest.java
> +		return System.getProperty("os.name").startsWith("Windows");
Sure! I'll look into the this issue https://github.com/diffplug/spotless/issues/710 and add it there.

2020-11-18 11:11 UTC, driv commented
> 
> 
> Thanks for the fix!

Thanks for your support! You make it really easy for people to contribute.