Improve handling for multiple targets
diffplug/spotless pull request #838
Opened 2021-04-08 22:07 UTC by bigdaz

Fix #835 by avoiding special treatment for multiple `String` targets.

2021-04-08 22:43 UTC, nedtwigg requested changes
Looks great, thanks! Two minor comments below.

2021-04-08 22:43 UTC, nedtwigg commented on plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
>  		} else {
I guess we don't need any of these `targets.length` special cases anymore. Your call whether we keep them or just loop over the array every time.

2021-04-08 22:43 UTC, nedtwigg commented on plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
> +			if (targetString.startsWith("**/") || targetString.startsWith("**\\")) {
Just noting that this changes our trigger from `**/*` to `**/`. I think it is a bugfix, but it's worth a mention in the changelog.

2021-04-09 21:00 UTC, nedtwigg commented
@bigdaz I'll make these changes myself and merge it later today, thanks for the PR!

2021-04-10 08:22 UTC, nedtwigg commented on plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
>  		} else {
Changed my mind, I think it's a bit easier to read to keep the special cases.

2021-04-10 08:23 UTC, nedtwigg commented on plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
> +			if (targetString.startsWith("**/") || targetString.startsWith("**\\")) {
Done!

2021-04-10 08:23 UTC, merged

2021-04-10 09:02 UTC, nedtwigg commented
Released in `plugin-maven 2.10.0` and `plugin-gradle 5.12.0`.

2021-04-10 13:51 UTC, bigdaz commented
Thanks for merging, Ned. I like the fact that the code is now simpler and the behaviour is more consistent.