Reinstall node if necessary
diffplug/spotless pull request #867
Opened 2021-05-13 09:04 UTC by fdw

If node has been deleted between Spotless installing it and using it
(for example because React's `build` removes everything from the `build`
dir), it is not re-installed.

Fixes #863

2021-05-13 09:05 UTC, fdw commented
I couldn't think of a good way to test this, unfortunately. If you have an idea, please share :)

2021-05-13 17:17 UTC, nedtwigg requested changes
- Run `spotlessApply`
- Did you [integration test](https://github.com/diffplug/spotless/blob/main/CONTRIBUTING.md#gradle---locally) on your machine to confirm that it fixed your problem?

2021-05-13 17:17 UTC, nedtwigg commented on lib/src/main/java/com/diffplug/spotless/npm/NodeServerLayout.java
> +	public static File getBuildDirFromNodeModulesDir(File nodeModulesDir) {
make it package-private, not public

2021-05-13 19:21 UTC, fdw commented
> Run spotlessApply

Oh, I'm so sorry. Fixed now.

> Did you integration test on your machine to confirm that it fixed your problem?

Yes, and it works :)

2021-05-13 19:21 UTC, fdw commented on lib/src/main/java/com/diffplug/spotless/npm/NodeServerLayout.java
> +	public static File getBuildDirFromNodeModulesDir(File nodeModulesDir) {
Done.

2021-05-13 21:09 UTC, merged

2021-05-13 22:41 UTC, nedtwigg commented
Shipped in `plugin-maven 2.11.1` and `plugin-gradle 5.12.5`

2021-05-14 06:49 UTC, fdw commented
That was very quick and nice. Thank you very much!