Java importOrder support for sorting wildcards last
diffplug/spotless pull request #954
Opened 2021-10-01 03:19 UTC by hakanai

Adds support for sorting wildcards after non-wildcards in the import list. Gradle config like so:

```
importOrder('java', 'javax', 'com.acme', '').wildcardsLast()
```

Not implemented here: Maven plugin support

Fixes #879.

![Allow edits from maintainers](https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)

After creating the PR, please add a commit that adds a bullet-point under the `-SNAPSHOT` section of [CHANGES.md](https://github.com/diffplug/spotless/blob/main/CHANGES.md), [plugin-gradle/CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md), and [plugin-maven/CHANGES.md](https://github.com/diffplug/spotless/blob/main/plugin-maven/CHANGES.md) which includes:

- [ ] a summary of the change
- either
    - [ ] a link to the issue you are resolving (for small changes)
    - [ ] a link to the PR you just created (for big changes likely to have discussion)

If your change only affects a build plugin, and not the lib, then you only need to update the `CHANGES.md` for that plugin.

If your change affects lib in an end-user-visible way (fixing a bug, updating a version) then you need to update `CHANGES.md` for both the lib and the build plugins.  Users of a build plugin shouldn't have to refer to lib to see changes that affect them.

This makes it easier for the maintainers to quickly release your changes :)

2021-10-01 03:27 UTC, hakanai commented
What to do about Maven? Do all new features have to be added for both at the same time to get in?

2021-10-01 05:03 UTC, tisoft commented
I could do maven support as soon as this is in

2021-10-01 19:29 UTC, nedtwigg commented
> Do all new features have to be added for both at the same time to get in?

Nope, from [our readme](https://github.com/diffplug/spotless#why-are-there-empty-squares):

> If you want to add Bazel support, we'd happily accept the PR even if it only supports the one formatter you use. And if you want to add FooFormatter support, we'll happily accept the PR even if it only supports the one build system you use. ... Once someone has filled in one square of the formatter/build system matrix, it's easy for interested parties to fill in any empty squares, since you'll now have a working example for every piece needed.

2021-10-01 19:35 UTC, nedtwigg requested changes
Great PR! Needs just a few minor changes.

2021-10-01 19:35 UTC, nedtwigg commented on lib/src/main/java/com/diffplug/spotless/java/ImportOrderStep.java
> +		return createFrom(false, importsFile);
replace false with `private static final boolean WILDCARDSLAST_DEFAULT`

2021-10-01 19:35 UTC, nedtwigg commented on lib/src/main/java/com/diffplug/spotless/java/ImportOrderStep.java
> +		return createFrom(false, importOrder);
replace false with `private static final boolean WILDCARDSLAST_DEFAULT`

2021-10-01 19:35 UTC, nedtwigg commented on plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JavaExtension.java
> +		public ImportOrderConfig wildcardsLast() {
Should follow this pattern

https://github.com/diffplug/spotless/blob/c687694377edfe2a9589f2be90ddb7645f6b40e3/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/JavaExtension.java#L119-L126

2021-10-01 22:45 UTC, hakanai commented
Requested changes made, separate commit for now but could squash later if necessary.

2021-10-01 22:49 UTC, nedtwigg commented
Run `spotlessApply` to fix CI and this is good :)

2021-10-01 22:53 UTC, hakanai commented
Results in no changes. Though `spotlessCheck` fails, it's on one of the dotfiles that I haven't actually touched.

2021-10-01 22:58 UTC, nedtwigg commented
Hm, very strange. Can you confirm that you have `origin/main` in your checkout? Maybe you called `origin` something else? CI is giving the failure I would expect around license dates.

https://app.circleci.com/pipelines/github/diffplug/spotless/1297/workflows/e52e8deb-cf23-4ff4-bf4f-f1027d15653d/jobs/7362

I can run `spotlessApply` myself, but I'd like to debug why yours isn't working. What dotfile is Spotless failing on?

2021-10-01 23:02 UTC, hakanai commented
It was `.editorconfig` but it looked like the diff contained the whole file so I'm guessing it's line endings.

I applied the diffs that were in the CI failure for the Java files so those should be OK now.

2021-10-01 23:19 UTC, merged

2021-10-02 02:37 UTC, nedtwigg commented
Fixed in `plugin-gradle 5.16.0`, thanks for the PR!

2021-10-02 10:54 UTC, jbduncan commented
Great addition @hakanai, so thank you for your PR. :)

2021-10-02 15:30 UTC, hakanai commented
Just glad I finally found a bit of time to do the work. Should reduce IDEA-related suffering at work quite a bit.