Issue 650 872 multi license headers
diffplug/spotless pull request #990
Opened 2021-11-09 17:09 UTC by igorbeslic

Fixes #650 
Fixes #872

2021-11-09 19:09 UTC, nedtwigg requested changes
Great PR! Only needs a few minor tweaks, plus docs + changelog entries. EDIT: I see you have an entry for `plugin-gradle/CHANGES`, we also need an entry for the root `CHANGES.md` also.

2021-11-09 19:09 UTC, nedtwigg commented on lib/src/main/java/com/diffplug/spotless/FormatterStep.java
> +	 * The provided filter must be serializable.
I think Strings are usually serializable ;-)

2021-11-09 19:09 UTC, nedtwigg commented on plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
> +		public LicenseHeaderConfig onlyIfMatches(String contentPattern) {
`onlyIfContentMatches`

2021-11-09 19:09 UTC, nedtwigg commented on plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
> +
I try not to comment on style issues that Spotless doesn't have rules for, but the blank lines within methods are bothering my eyes a little bit. It's just too different from the style we use elsewhere. Please add a commit that removes blank lines from within the new methods you added.

2021-11-09 21:15 UTC, igorbeslic commented
@nedtwigg Would it be fine if I just update this existing PR with commit with changes??
PS. Don't be afraid to point code style problems I'll adopt it. I also come from strict "style and convention tribe". I understand it 💯

2021-11-09 21:16 UTC, nedtwigg commented
I prefer new commits to reduce review burden :)

2021-11-11 22:47 UTC, nedtwigg commented
You've got some spotbugs warnings. You can view locally with `spotbugsMain`, here's the issue from CI:

https://8354-34685800-gh.circle-artifacts.com/0/lib/build/spotbugs/main.html#NP_NONNULL_RETURN_VIOLATION

2021-11-12 15:03 UTC, igorbeslic commented
> You've got some spotbugs warnings. You can view locally with `spotbugsMain`, here's the issue from CI:
> 
> https://8354-34685800-gh.circle-artifacts.com/0/lib/build/spotbugs/main.html#NP_NONNULL_RETURN_VIOLATION

:) @nedtwigg  thank you for patience - I superficially went through contributing and code_of_conduct - it is cause of glitches you see in my PR

2021-12-01 05:56 UTC, merged

2021-12-01 05:56 UTC, nedtwigg commented
Very sorry for the long delay, this is an excellent PR that deserved to be merged and released quicker.

2021-12-01 17:22 UTC, nedtwigg commented
Published in `plugin-gradle/6.0.1`.